/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEMA1_H_RPCGEN
#define _TEMA1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct request_t {
	char *id;
	int type;
	char *token;
	char *additional;
	char *cmd;
};
typedef struct request_t request_t;

struct response_t {
	char *result;
	char *req_token;
	char *acc_token;
	char *ref_token;
	int valability;
};
typedef struct response_t response_t;

#define TEMA1_PROG 1
#define TEMA1_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define request_authorization 1
extern  response_t * request_authorization_1(request_t *, CLIENT *);
extern  response_t * request_authorization_1_svc(request_t *, struct svc_req *);
#define request_access_token 2
extern  response_t * request_access_token_1(request_t *, CLIENT *);
extern  response_t * request_access_token_1_svc(request_t *, struct svc_req *);
#define validate_delegated_action 3
extern  response_t * validate_delegated_action_1(request_t *, CLIENT *);
extern  response_t * validate_delegated_action_1_svc(request_t *, struct svc_req *);
#define approve_request_token 4
extern  response_t * approve_request_token_1(request_t *, CLIENT *);
extern  response_t * approve_request_token_1_svc(request_t *, struct svc_req *);
extern int tema1_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define request_authorization 1
extern  response_t * request_authorization_1();
extern  response_t * request_authorization_1_svc();
#define request_access_token 2
extern  response_t * request_access_token_1();
extern  response_t * request_access_token_1_svc();
#define validate_delegated_action 3
extern  response_t * validate_delegated_action_1();
extern  response_t * validate_delegated_action_1_svc();
#define approve_request_token 4
extern  response_t * approve_request_token_1();
extern  response_t * approve_request_token_1_svc();
extern int tema1_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_request_t (XDR *, request_t*);
extern  bool_t xdr_response_t (XDR *, response_t*);

#else /* K&R C */
extern bool_t xdr_request_t ();
extern bool_t xdr_response_t ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEMA1_H_RPCGEN */
