/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tema1.h"

bool_t
xdr_request_t (XDR *xdrs, request_t *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->id, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->additional, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->cmd, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_response_t (XDR *xdrs, response_t *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->result, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->req_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->acc_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->ref_token, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->valability))
		 return FALSE;
	return TRUE;
}
